name: Docs Uptime

on:
  schedule:
    # Runs at midnight 00:00 UTC every Friday
    - cron: '0 0 * * 5'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false  

    - name: Set up GitHub credentials
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Add upstream remote and fetch
      run: |
        git remote add upstream https://github.com/freebsd/freebsd-doc.git
        git fetch upstream
        git checkout main

    - name: Attempt full merge from upstream
      id: full_merge
      continue-on-error: true
      run: |
        git merge upstream/main

    - name: Fallback to fast-forward only if full merge fails
      if: steps.full_merge.outcome != 'success'
      run: |
        echo "⚠️ Full merge failed. Attempting fast-forward merge..."
        git merge --ff-only upstream/main

    - name: Push updates to fork
      run: |
        git push origin main
